# Run Config Server on port 8888
server.port=8888

# Application name
spring.application.name=config-server

# Use native profile (local folder-based config)
spring.profiles.active=native

# Where config files will be stored
spring.cloud.config.server.native.search-locations=classpath:/config-repo
